In [446]:
import re
import jieba
import jieba.analyse
import json
import random
import operator
import numpy as np
import pandas as pd
from collections import defaultdict
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer, TfidfTransformer
from sklearn.decomposition import NMF, LatentDirichletAllocation

In [2]:
from elasticsearch import Elasticsearch
import elasticsearch.helpers
from datetime import datetime

In [3]:
es = Elasticsearch([{'host': 'localhost', 'port': 9200}])

In [4]:
# Find top10
res = es.search(index='facebook', doc_type='user', body= {'query': {'match': {'gender': 'female'}}})
print("%d documents found" % res['hits']['total'])

58 documents found


In [5]:
# Take all result
users = list(elasticsearch.helpers.scan(es, index='facebook', doc_type='user'))
total_users = [user['_id'] for user in users]
total_user_with_gender = [(user['_id'], user['_source'].get('gender')) for user in users]
print(len(total_user_with_gender))

143


In [6]:
no_message = ['1618047998214350', '1624029027647185', '1454298984658260', '1805190672831590']
foreigners = ['1695358370488750', '10213401737335928', '1532260126834371', '10154597524691479', '10155404471078548', '10158882655745234']

In [7]:
total_users = [user for user in total_users if user not in (no_message + foreigners)]
print(len(total_users))

133


In [8]:
user_dict = {'male': [], 'female': []}
for user in total_user_with_gender:
    if user[0] not in (no_message + foreigners):
        if user[1] == 'male':
            user_dict['male'].append(user[0])
        else:
            user_dict['female'].append(user[0])

In [9]:
print('male: ' + str(len(user_dict['male'])) + '\nfemale: ' + str(len(user_dict['female'])))

male: 79
female: 54


In [10]:
# Filtering urls
def filtering_url(messages):
    filtered_messages = [re.sub('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', '', message.replace('\n', '').replace('\r', '')) for message in messages]
    return filtered_messages

In [11]:
# Mapping user posts
def get_posts(users):
    posts_dic = {}
    for user in users:
        # print(user)
        posts = list(elasticsearch.helpers.scan(es, query={'query': {'match': {'user_id': user}}}, index='facebook', doc_type='post'))
        messages = [post['_source'].get('message') for post in posts if post['_source'].get('message') != '']
        #print(message)
        filtered_messages = filtering_url(messages)
        posts_dic[user] = filtered_messages
    return posts_dic

In [12]:
total_posts = get_posts(total_users)
male_posts_dict = get_posts(user_dict['male'])
female_posts_dict = get_posts(user_dict['female'])

# Using jieba as Chinese tokenizer, and calculating TFIDF

In [13]:
# Using jieba to tokenize user posts
def tokenize_posts(user_posts):
    seg_posts = {}
    for key, messages in user_posts.items():
        seg_posts[key] = [' '.join(jieba.cut(message, cut_all = False)) for message in messages]
    return seg_posts

In [14]:
male_seg_posts = tokenize_posts(male_posts_dict)
female_seg_posts = tokenize_posts(female_posts_dict)

Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.695 seconds.
Prefix dict has been built succesfully.


In [15]:
# Display tfidf score
def display_scores(vectorizer, tfidf_result):
    # http://stackoverflow.com/questions/16078015/
    scores = zip(vectorizer.get_feature_names(),
                 np.asarray(tfidf_result.sum(axis=0)).ravel())
    sorted_scores = sorted(scores, key=lambda x: x[1], reverse=True)
    index_scores = []
    for index, item in enumerate(sorted_scores):
        index_scores.append((index, item[1]))
    return sorted_scores

In [16]:
def calculate_tfidf(seg_posts):
    corpus = [segment for key, segments in seg_posts.items() for segment in segments]
    tfidf_vectorizer = TfidfVectorizer()
    tfidf = tfidf_vectorizer.fit_transform(corpus)
    tfidf_features = tfidf_vectorizer.get_feature_names()
    
    sorted_scores = display_scores(tfidf_vectorizer, tfidf)
    return sorted_scores

In [17]:
male_tfidf_scores = calculate_tfidf(male_seg_posts)
female_tfidf_scores = calculate_tfidf(female_seg_posts)

In [18]:
male_bag_of_words = [word[0] for word in male_tfidf_scores[:100]]
female_bag_of_words = [word[0] for word in female_tfidf_scores[:100]]

# Graph-based word categorization

In [19]:
%%time
word_index = {}
index = 1

#Building word index dictionary
for key, messages in total_posts.items():
    for message in messages:
        for word in list(message):
            if word not in word_index:
                word_index[word] = index
                index += 1

CPU times: user 544 ms, sys: 0 ns, total: 544 ms
Wall time: 555 ms


In [20]:
def building_weighted_graph(word_graph):
    weighted_word_graph = {}
    # Finding the maximun value of word frequency
    max_freq = max(word_graph.items(), key=operator.itemgetter(1))[1]

    for key, value in word_graph.items():
        weight = value / max_freq
        weighted_word_graph[key] = weight 
    return weighted_word_graph

In [21]:
def building_word_graph(user_posts):
    word_graph = {}
    for key, messages in user_posts.items():
        for message in messages:
            words = list(message)
            
            for i in range(len(words)-1):
                if (words[i], words[i+1]) not in word_graph:
                    word_graph[(words[i], words[i+1])] = 1
                else:
                    word_graph[(words[i], words[i+1])] += 1
    weighted_word_graph = building_weighted_graph(word_graph)
    return weighted_word_graph

In [22]:
male_weighted_graph = building_word_graph(male_posts_dict)
female_weighted_graph = building_word_graph(female_posts_dict)

In [23]:
import networkx as nx
import plotly.plotly as py
from plotly.graph_objs import *

In [24]:
G = nx.random_geometric_graph(200, 1)
# position is stored as node attribute data for random_geometric_graph
pos = nx.get_node_attributes(G, 'pos')

In [25]:
edge_trace = Scatter(
    x=[], 
    y=[], 
    line=Line(width=0.5,color='#888'),
    hoverinfo='none',
    mode='lines')

# Topic Modeling

In [396]:
with open('./extra_dictionary/stop_words.txt','r') as file:
    stopwords = [line.rstrip('\n') for line in file]

In [397]:
def print_top_words(model, feature_names, n_top_words):
    for topic_idx, topic in enumerate(model.components_):
        print("Topic #%d:" % topic_idx)
        print(" ".join([feature_names[i]
        for i in topic.argsort()[:-n_top_words - 1:-1]]))
    print()

In [398]:
def stem_words(sentence):
    stemmed_term_xd = re.sub(r'(x|X)+(D|d)+', 'xd', sentence)
    stemmed_term_qq = re.sub(r'(q|Q)+(q|Q)+', 'qq', stemmed_term_xd)
    stemmed_digit = re.sub(r'([0-9])([0-9])*', '', stemmed_term_qq)
    words = list(jieba.cut(stemmed_digit, cut_all = False))
    stemmed_sentence = ' '.join([word for word in words if word not in stopwords])
    return stemmed_sentence

In [399]:
matched_id = []
corpus = []
for key, messages in total_posts.items():
    for message in messages:
        matched_id.append(key)
        stemmed_message = stem_words(message)
        corpus.append(stemmed_message)

In [400]:
print(len(matched_id))
print(len(corpus))

84497
84497


In [401]:
tfidf_vectorizer = TfidfVectorizer()
tfidf = tfidf_vectorizer.fit_transform(corpus)

In [402]:
tfidf_sorted_scores = display_scores(tfidf_vectorizer, tfidf)

In [403]:
bag_of_words = [word[0] for word in tfidf_sorted_scores[:200]]

In [405]:
tf_vectorizer = CountVectorizer()
tf = tf_vectorizer.fit_transform(corpus)

In [406]:
tfidf_feature_names = tfidf_vectorizer.get_feature_names()

In [407]:
lda = LatentDirichletAllocation(n_topics=4, max_iter=5,
                                learning_method='online',
                                learning_offset=50.,
                                random_state=0)

In [408]:
lda.fit(tf)

/usr/local/lib/python3.5/dist-packages/sklearn/decomposition/online_lda.py:294: DeprecationWarning:

n_topics has been renamed to n_components in version 0.19 and will be removed in 0.21



LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
             evaluate_every=-1, learning_decay=0.7,
             learning_method='online', learning_offset=50.0,
             max_doc_update_iter=100, max_iter=5, mean_change_tol=0.001,
             n_components=10, n_jobs=1, n_topics=4, perp_tol=0.1,
             random_state=0, topic_word_prior=None,
             total_samples=1000000.0, verbose=0)

In [409]:
distribution = lda.fit_transform(tf)

/usr/local/lib/python3.5/dist-packages/sklearn/decomposition/online_lda.py:294: DeprecationWarning:

n_topics has been renamed to n_components in version 0.19 and will be removed in 0.21



In [410]:
print(distribution)

[[ 0.25        0.25        0.25        0.25      ]
 [ 0.02778917  0.02780652  0.91659435  0.02780995]
 [ 0.03648737  0.03571534  0.8920818   0.03571549]
 ..., 
 [ 0.02130263  0.02083519  0.52798044  0.42988173]
 [ 0.23870814  0.00642995  0.74845113  0.00641078]
 [ 0.60778559  0.0625093   0.26719522  0.06250988]]


In [411]:
tf_feature_names = tf_vectorizer.get_feature_names()

In [412]:
print_top_words(lda, tf_feature_names, 20)

Topic #0:
xd 今天 真的 大家 明天 qq 可以 謝謝 好像 還有 加油 一個 看到 還是 哈哈 一起 不過 好多 開心 開始
Topic #1:
ahq 圖靈機 my 哈哈哈 啊啊啊 幹幹 正在 go so be 程式 with day 呵呵 ya all we tpa lol by
Topic #2:
可以 真的 一個 知道 就是 還是 不是 時候 不要 覺得 一直 這樣 這麼 大家 今天 如果 沒有 只是 很多 事情
Topic #3:
參加 活動 好久 一起 神魔 鎖鎖鎖 __ 作業 快來 ___ 儒佳 打卡 網址 問卷 不見 飲料 gg de 分享 lab



In [438]:
i = 0
user_topic_distribution = defaultdict(lambda:defaultdict(list))
for values in distribution:
    user_id = matched_id[i]
    # print(user_id)
    maximum = max(values)
    if maximum != 0.25:
        index = list(values).index(max(values))
        user_topic_distribution[user_id][index].append(maximum)
    i += 1

In [501]:
user_topic_count = defaultdict(lambda:defaultdict(lambda:0))
for key, items in user_topic_distribution.items():
    if key not in user_topic_count:
        user_topic_count[key][0] = 0
        user_topic_count[key][1] = 0
        user_topic_count[key][2] = 0
        user_topic_count[key][3] = 0
    for topic, values in items.items():
        user_topic_count[key][topic] = len(values)

In [512]:
user_topic_table = [['id', 'topic0_count', 'topic1_count', 'topic2_count', 'topic3_count']]
for key, items in user_topic_count.items():
    scores = [key]
    for i in range(4):
        scores.append(user_topic_count[key][i])
    user_topic_table.append(scores)

In [513]:
headers = user_topic_table.pop(0)
df = pd.DataFrame(user_topic_table, columns=headers)
df

id  topic0_count  topic1_count  topic2_count  topic3_count
0     1822107337815837             6             1            10             4
1     1808122152538948           414            99           123            50
2     1525066240878271            63            30            45            17
3    10210988536529598            25            43            41            28
4     1386097208093454           311            90           413            86
5     1896221243728018            43            46            58            49
6     1634011049952111            33            27            47            15
7     1513944438661823            53            29            59            17
8     1840120512668185           151            64           419            30
9     1721752347837052            35             7            39            14
10    1736602939687427            49            28            45            40
11   10208698865103060            52            30           131            37
12    1755898664424794           147            93           165            47
13    1624663430897732           224           177           260           100
14    1517846504925449           285           110           729            73
15    1510694482285844            79            24            88            23
16    1442789662480454            70            20           115            21
17    1780384911978670           498           234           809           119
18    1425644360862465            34             7            40            10
19    1372981062791429             4             5             3             1
20    1929201887095729           275           114           277            82
21    1772954002721149          1209           365          1594           272
22   10213721570903289            57           117            48            38
23    1755437391140657           151            75           121            73
24    1462695893826968             7             1             5             2
25    1384036221681615           219            40           148            48
26    1563244917028120           144            64           257            29
27    1625035490848760           296            69           530            66
28    1637654792912553           186           140           183            74
29    1748447515171073          1687           584          2039           404
..                 ...           ...           ...           ...           ...
103   1803136159999174            93           252           169            82
104   1530185160345344            65            15            56            24
105   1599238036786208            88            37            73            41
106   1803804869633868           543           125          1135            84
107   1746678138681672           149            72           242            88
108  10213276568926800            68            13            37            17
109   1341342575915634           274           164           332           156
110   1495887873803756             3             2             3             2
111   1485478021473396            63             7           249            15
112   1459704867444437           160            32           252            44
113   1441585192605037            36            33            70             9
114  10214994163795546             6             1             3             2
115   1594133623932600           123            71           310            54
116   1380347355348220            19             3             9            11
117   1415853895166805            12             5             7             6
118  10212229002914065           435            77           407            96
119   1682785845070091            23            10            21             6
120  10209884878146900            91            40            96            37
121   1785137904835208           135            13            96      